def app

pipeline {
    agent any
    stages {
        stage('SCM') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/JenkinsTestProject']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/executeautomation/SeleniumWithCucucumber']]])
            }
        }
        stage('Build image') {
            steps{
                script {
                    app = docker.build("testproject/agent:latest")
                }
            }
        }


        stage('Check Image') {
            steps {
                script {
                    container = app.run()
                    container.inside {
                        sh 'java --version'
                    }
                    container.stop()
                }
            }
        }
    }
}